"""add banned users table

Revision ID: 588c2370bd02
Revises: 0e5b3eb05d89
Create Date: 2026-06-19 10:13:13.349501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588c2370bd02'
down_revision = '0e5b3eb05d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_users',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned_users')
    # ### end Alembic commands ###
