"""add phone_number to user

Revision ID: 6f495b6f4d8c
Revises: 8b7bfc5a6886
Create Date: 2026-05-10 09:29:15.290004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f495b6f4d8c'
down_revision = '8b7bfc5a6886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=16), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
